
/********************************************************************************
 *										*
 *				 M A C E K					*
 *		("Matroids Also Computed Efficiently" Kit)			*
 *										*
 * A set of tools and routines for computations with representable matroids.	*
 * Copyright (C) 2001--2011  Petr Hlineny.					*
 *										*
 *   This program is free software; you can redistribute it and/or modify	*
 *   it under the terms of the GNU General Public License as published by	*
 *   the Free Software Foundation; either version 2 of the License, or		*
 *   (at your option) any later version.					*
 *   You should have received a copy of the GNU General Public License		*
 *   along with this program; if not, write to the Free Software		*
 *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.	*
 * 										*
 * See the top-level "ABOUT" and "doc/ *" files for more information.		*
 *										*
 ********************************************************************************/











/**
 * This file is provided for third-party additions to the frame-commands.
 * See the master file frcoms.c.
 * 
 * .....
 * 
**/



#if FR_COMSEXTRA<=0

/**     
 * Put the additional command-handling functions here...
 * 
**/



#else

/**     
 * Put the corresponding entries to the comhdefs[] array here...
 * (See the description of structure commhandles in fr.h.)
 * 
**/



#endif     


































